title: Release History Dashboard
description: Track and analyze release approvals and deployment metrics
theme: jekyll-theme-minimal
baseurl: /deploy-test

# Release files configuration
include:
  - "releases/*.md"

# Default layout for release files
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "releases"
      type: "pages"
    values:
      layout: "release"

# Plugins
plugins:
  - jekyll-github-pages 