title: Release History
description: History of all approved releases with approval times
theme: jekyll-theme-minimal

collections:
  releases:
    output: true
    permalink: /releases/:name

defaults:
  - scope:
      path: ""
      type: "releases"
    values:
      layout: "release"

plugins:
  - jekyll-github-pages 