title: Release History
description: History of all approved releases with approval times
theme: jekyll-theme-minimal

# Release files configuration
include:
  - "releases/*.md"

# Default layout for release files
defaults:
  - scope:
      path: "releases"
      type: "pages"
    values:
      layout: "release"

# Plugins
plugins:
  - jekyll-github-pages 