# GitHub App Configuration
app:
  name: "Release Approval App"
  email: "release-approval[bot]@users.noreply.github.com"
  token_action: "tibdex/github-app-token@v2"

# Reviewers Configuration
reviewers:
  - keren-cw
  - ingrid-cw

# Git Configuration
git:
  user:
    name: "Release Approval App"
    email: "release-approval[bot]@users.noreply.github.com"
  commit_messages:
    add_release: "docs: add release details for %s"
    update_release: "docs: update release details with approval date and approvers" 