# GitHub App Configuration
app:
  name: "QE Release Approval"
  token_action: "actions/create-github-app-token@v1"

# Reviewers Configuration
reviewers:
  - keren-cw
  - ingrid-cw

# Git Configuration
git:
  user:
    name: "QE Release Approval"
  commit_messages:
    add_release: "docs: add release details for %s"
    update_release: "docs: update release details with approval date and approvers" 