name: Release Promotion Workflow

on:
  release:
    types: [prereleased]

permissions:
  contents: write
  pull-requests: write

jobs:
  create_approval_pr:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create_pr.outputs.pr_number }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get release info
        id: release_info
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const release = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id
            });
            
            core.setOutput('tag_name', release.data.tag_name);
            core.setOutput('release_name', release.data.name || release.data.tag_name);
            core.setOutput('created_at', release.data.created_at);
            core.setOutput('body', release.data.body || '');

      - name: Create release approval branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b release-approval-${{ steps.release_info.outputs.tag_name }}

      - name: Create release details file
        run: |
          mkdir -p releases
          cat > releases/${{ steps.release_info.outputs.tag_name }}.md << EOL
          # Release Approval: ${{ steps.release_info.outputs.release_name }}
          
          - **Tag**: ${{ steps.release_info.outputs.tag_name }}
          - **Release Date**: ${{ steps.release_info.outputs.created_at }}
          
          ## Release Notes
          ${{ steps.release_info.outputs.body }}
          EOL
          
          git add releases/${{ steps.release_info.outputs.tag_name }}.md
          git commit -m "docs: add release details for ${{ steps.release_info.outputs.tag_name }}"
          git push origin release-approval-${{ steps.release_info.outputs.tag_name }}

      - name: Create Pull Request
        id: create_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Release Approval: ${process.env.RELEASE_NAME}`,
              body: `This PR contains the release details for ${process.env.TAG_NAME}.
              
              Please review and approve. The release will be promoted once the PR is merged.`,
              head: `release-approval-${process.env.TAG_NAME}`,
              base: 'main'
            });
            
            // Add reviewers
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.data.number,
              reviewers: ['keren-cw', 'ingrid-cw']
            });
            
            core.setOutput('pr_number', pr.data.number);
        env:
          TAG_NAME: ${{ steps.release_info.outputs.tag_name }}
          RELEASE_NAME: ${{ steps.release_info.outputs.release_name }}

  promote_release:
    needs: create_approval_pr
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ needs.create_approval_pr.outputs.pr_number }};
            
            // Check if PR is merged
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            
            if (!pr.data.merged) {
              core.setFailed('Pull request must be approved and merged before release promotion');
              return;
            }

      - name: Promote to production release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              prerelease: false,
              draft: false
            });
