name: Release Approval

on:
  release:
    types: [published]
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

env:
  APP_NAME: "QE Release Approval"

jobs:
  create-approval-pr:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: Configure Git
        run: |
          git config user.name "${{ env.APP_NAME }}"
          git config user.email "${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git
      
      - name: Get release details
        id: release
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "date=$(TZ='America/Sao_Paulo' date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          
      - name: Create release branch
        run: |
          git checkout -b approval-${{ steps.release.outputs.tag }}
          
      - name: Update releases.json
        run: |
          mkdir -p docs/github_page/_data
          if [ ! -f docs/github_page/_data/releases.json ]; then
            echo '{"releases":[]}' > docs/github_page/_data/releases.json
          fi
          
          jq --arg tag "${{ steps.release.outputs.tag }}" \
             --arg date "${{ steps.release.outputs.date }}" \
             --arg title "Release ${{ steps.release.outputs.tag }}" \
             --arg notes "${{ github.event.release.body }}" \
             '.releases += [{
               "title": $title,
               "tag": $tag,
               "release_date": $date,
               "notes": $notes
             }]' docs/github_page/_data/releases.json > temp.json && mv temp.json docs/github_page/_data/releases.json
          
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_BODY: |
            This PR was automatically created to track the approval of release ${{ steps.release.outputs.tag }}.

            Release Link: https://github.com/${{ github.repository }}/releases/tag/${{ steps.release.outputs.tag }}
        run: |
          git add docs/github_page/_data/releases.json
          git -c user.name="${{ env.APP_NAME }}" -c user.email="${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com" commit -m "Release Approval: ${{ steps.release.outputs.tag }}"
          git push -u origin approval-${{ steps.release.outputs.tag }}
          
          gh pr create \
            --title "Release Approval: ${{ steps.release.outputs.tag }}" \
            --body "$PR_BODY" \
            --base main \
            --head approval-${{ steps.release.outputs.tag }}

  update-release-status:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'approval-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Generate App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: Configure Git
        run: |
          git config user.name "${{ env.APP_NAME }}"
          git config user.email "${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git
          
      - name: Get release tag
        id: release
        run: |
          TAG=${GITHUB_HEAD_REF#approval-}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "approval_date=$(TZ='America/Sao_Paulo' date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          
      - name: Get PR approvers
        id: approvers
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          PR_NUMBER=$(gh pr list --search "head:approval-${{ steps.release.outputs.tag }}" --state merged --json number -q '.[0].number')
          APPROVERS=$(gh pr view $PR_NUMBER --json reviews -q '.reviews[].author.login' | sort -u | tr '\n' ',' | sed 's/,$//')
          echo "list=$APPROVERS" >> $GITHUB_OUTPUT
          
      - name: Update releases.json
        run: |
          jq --arg tag "${{ steps.release.outputs.tag }}" \
             --arg date "${{ steps.release.outputs.approval_date }}" \
             --arg approvers "${{ steps.approvers.outputs.list }}" \
             --argjson minutes "$(( ($(date -u +%s) - $(date -u -d "${{ github.event.pull_request.created_at }}" +%s)) / 60 ))" \
             '.releases |= map(
               if .tag == $tag then
                 . + {
                   "approval_date": $date,
                   "approvers": $approvers,
                   "approval_time_minutes": $minutes
                 }
               else . end
             )' docs/github_page/_data/releases.json > temp.json && mv temp.json docs/github_page/_data/releases.json
          
      - name: Update release status
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh release edit ${{ steps.release.outputs.tag }} --prerelease=false --latest
          
      - name: Commit and push changes
        run: |
          git add docs/github_page/_data/releases.json
          git commit -m "Update release status: ${{ steps.release.outputs.tag }}"
          git push

  pages:
    needs: [update-release-status]
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Generate App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      
      - name: Configure Git
        run: |
          git config user.name "${{ env.APP_NAME }}"
          git config user.email "${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/github_page
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
