name: Release Approval

on:
  release:
    types: [published]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  create-approval-pr:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Generate App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
      
      - name: Get release details
        id: release
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          
      - name: Create release branch
        run: |
          git config --global user.name "Release Approval App"
          git config --global user.email "release-approval[bot]@users.noreply.github.com"
          git checkout -b release-approval-${{ steps.release.outputs.tag }}
          
      - name: Update releases.json
        run: |
          if [ ! -f releases.json ]; then
            echo '{"releases":[]}' > releases.json
          fi
          
          jq --arg tag "${{ steps.release.outputs.tag }}" \
             --arg date "${{ steps.release.outputs.date }}" \
             --arg title "Release ${{ steps.release.outputs.tag }}" \
             --arg notes "${{ github.event.release.body }}" \
             '.releases += [{
               "title": $title,
               "tag": $tag,
               "release_date": $date,
               "notes": $notes
             }]' releases.json > temp.json && mv temp.json releases.json
          
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git add releases.json
          git commit -m "Release Approval: ${{ steps.release.outputs.tag }}"
          git push -u origin release-approval-${{ steps.release.outputs.tag }}
          
          gh pr create \
            --title "Release Approval: ${{ steps.release.outputs.tag }}" \
            --body "This PR was automatically created to track the approval of release ${{ steps.release.outputs.tag }}." \
            --base main \
            --head release-approval-${{ steps.release.outputs.tag }}

  update-release-status:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && startsWith(github.event.pull_request.head.ref, 'release-approval-')
    runs-on: ubuntu-latest
    steps:
      - name: Generate App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.event.pull_request.head.ref }}
          
      - name: Get release tag
        id: release
        run: |
          TAG=${GITHUB_HEAD_REF#release-approval-}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "approval_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          
      - name: Update releases.json
        run: |
          jq --arg tag "${{ steps.release.outputs.tag }}" \
             --arg date "${{ steps.release.outputs.approval_date }}" \
             --arg approver "${{ github.event.review.user.login }}" \
             --argjson minutes "$(( ($(date -u +%s) - $(date -u -d "${{ github.event.pull_request.created_at }}" +%s)) / 60 ))" \
             '.releases |= map(
               if .tag == $tag then
                 . + {
                   "approval_date": $date,
                   "approvers": $approver,
                   "approval_time_minutes": $minutes
                 }
               else . end
             )' releases.json > temp.json && mv temp.json releases.json
          
      - name: Commit and push changes
        run: |
          git config --global user.name "Release Approval App"
          git config --global user.email "release-approval[bot]@users.noreply.github.com"
          git add releases.json
          git commit -m "Update release status: ${{ steps.release.outputs.tag }}"
          git push
          
      - name: Auto-merge PR
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch

  pages:
    needs: [update-release-status]
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Generate App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: main
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
