name: Release Promotion Workflow

on:
  release:
    types: [prereleased]

# Add permissions block at workflow level
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  request_approval:
    runs-on: ubuntu-latest
    environment: 'production'  # Environment configured with approvers
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Get release notes and assign reviewers
        id: release_info
        uses: actions/github-script@v6
        with:
          # Explicitly set token permissions
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const release = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id
            });
            
            // Identify reviewers based on release notes content
            const releaseNotes = release.data.body;
            const reviewers = ['keren-cw', 'ingrid-cw']; // Fixed example, can be dynamic
            
            return {
              releaseId: release.data.id,
              reviewers: reviewers
            };

      - name: Promote to production release
        if: success()
        uses: actions/github-script@v6
        with:
          # Explicitly set token permissions
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              prerelease: false,
              draft: false
            });
